openapi: 3.0.0
info:
  title: Jobs API
  version: '1.0'
servers:
  - url: https://temp-jobs-api-lle0.onrender.com/api/v1
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '200':
          description: User successfully registered.
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User successfully logged in.
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
      responses:
        '200':
          description: Job successfully created.
      security:
        - bearer: []
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      responses:
        '200':
          description: List of jobs retrieved successfully.
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      responses:
        '200':
          description: Job retrieved successfully.
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRequestRequest'
      responses:
        '200':
          description: Job successfully updated.
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      responses:
        '200':
          description: Job successfully deleted.
      security:
        - bearer: []
components:
  schemas:
    RegisterUserRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    CreateJobRequest:
      type: object
      required:
        - company
        - position
      properties:
        company:
          type: string
        position:
          type: string
    NewRequestRequest:
      type: object
      required:
        - company
        - position
      properties:
        company:
          type: string
        position:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
